[package]
name = "lolei-chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
rand = "0.8.5"
sdl2 = { version = "0.37.0", features = ["bundled"] }
